name: Docker Build and Push  # Nom du workflow

on:
  push:
    branches:
      - master  # Déclenche le workflow sur un push dans la branche master
  workflow_dispatch:  # Permet le déclenchement manuel du workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise la dernière version d'Ubuntu comme environnement d'exécution

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Récupère le code du dépôt GitHub

      - name: Set up JDK 17
        uses: actions/setup-java@v2  # Configure Java Development Kit (JDK) 17
        with:
          distribution: 'adopt'  # Utilise la distribution AdoptOpenJDK
          java-version: '17'  # Spécifie la version 17 de Java

      - name: Cache Gradle packages
        uses: actions/cache@v2  # Met en cache les dépendances Gradle
        with:
          path: ~/.gradle/caches  # Spécifie le chemin du cache Gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}  # Clé de cache unique basée sur le système d'exploitation et les fichiers Gradle
          restore-keys: |
            ${{ runner.os }}-gradle-  # Clés de restauration pour le cache

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew  # Donne les permissions d'exécution au script gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar  # Construit le fichier JAR avec Gradle

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Configure Docker Buildx pour supporter les builds multi-architecture
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Configure Docker Buildx pour supporter les builds multi-architecture (duplicata, peut être supprimé)

      - name: Login to Docker Hub
        uses: docker/login-action@v1  # Se connecte à Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Utilise le nom d'utilisateur Docker Hub stocké dans les secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Utilise le mot de passe Docker Hub stocké dans les secrets

      - name: Build and push Docker image
        uses: docker/build-push-action@v2  # Construit et pousse l'image Docker
        with:
          context: .  # Utilise le contexte actuel pour la construction de l'image
          push: true  # Pousse l'image vers le registre Docker après la construction
          platforms: linux/amd64,linux/arm64,linux/arm/v7  # Construit l'image pour plusieurs architectures
          tags: cedsanc/bagueton-api:latest  # Tag de l'image Docker
